name: LoreAttribute
version: 1.0.0
main: dev.charlieveg.loreattribute.LoreAttributePlugin
author: charlieveg
api-version: 1.8
description: Advanced lore-based attribute system with battle inventory
commands:
  latr:
    description: Lore attribute main command
    usage: /latr [help|add|set|type|show]
    permission: loreattribute.use
  restriction:
    description: Equipment restriction system command
    usage: /restriction [reload|check|test|info]
    permission: loreattribute.restriction
permissions:
  loreattribute.use:
    description: Allows use of lore attribute commands
    default: op
  loreattribute.admin:
    description: Admin permissions for lore attribute
    default: op
  loreattribute.restriction:
    description: Allows use of equipment restriction commands
    default: op 